apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  labels:
    app: users-api
type: Opaque
stringData:
  MongoDbSettings__ConnectionString: "mongodb://mongodb:27017"
  JwtSettings__SecretKey: "FiapCloudGames_Demo_SecretKey_Com_Pelo_Menos_256_Bits_Para_HMAC_SHA256!"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
